const Map<String, String> enUS = {
  // ── Common ─────────────────────────────────────────────────────────
  'common.back': 'Back',
  'common.home': 'Home',
  'common.map': 'Map',
  'common.community': 'Community',
  'common.profile': 'Profile',
  'common.alerts': 'Alerts',
  'common.help': 'Help',
  'common.coordination': 'Coordination',
  'common.next': 'Next',
  'common.save': 'Save',
  'common.saving': 'Saving',
  'common.got_it': 'Got it',
  'common.retry': 'Try again',
  'common.rating': 'rating',  'common.ratings': 'ratings',
  'common.active': 'active',
  'common.cancel': 'Cancel',
  'common.accept': 'Accept',
  'common.accepting': 'Accepting',
  'common.call': 'Call',
  'common.urgent': 'Urgent',
  'common.reject': 'Reject',
  'common.approve': 'Approve',
  'common.delete': 'Delete',
  'common.start': 'Start',
  'common.join': 'Join',
  'common.chat': 'Chat',
  'common.message': 'Message',
  'common.send': 'Send',
  'common.publish': 'Publish',
  'common.publishing': 'Publishing...',
  'common.sending': 'Sending...',
  'common.search': 'Search',
  'common.improve': 'Improve',
  'common.not_provided': 'Not provided',
  'common.not_available': 'Not available',
  'common.pending': 'Pending',
  'common.approved': 'Approved',
  'common.rejected': 'Rejected',

  // ── Language ───────────────────────────────────────────────────────
  'language.label': 'Language',
  'language.en': 'EN',
  'language.choose': 'Choose Language',
  'language.ur': 'اردو',

  // ── Role Selection ─────────────────────────────────────────────────
  'role.selection.title': 'I want to...',
  'role.selection.subtitle': 'Choose how you\'d like to help your community',
  'role.request_help.title': 'Request Help',
  'role.request_help.description':
      'Submit a request for assistance\nfrom volunteers in your area',
  'role.volunteer.title': 'Verify as Volunteer',
  'role.volunteer.description':
      'Browse and respond to\nhelp requests in your area',

  // ── Auth ───────────────────────────────────────────────────────────
  'auth.login.welcome': 'Welcome Back',
  'auth.login.subtitle': 'Sign in to continue helping your community.',
  'auth.email.label': 'Email Address',
  'auth.email.hint': 'example@email.com',
  'auth.password.label': 'Password',
  'auth.password.hint': 'Enter your password',
  'auth.password.create_hint': 'Create a password',
  'auth.password.confirm_label': 'Confirm Password',
  'auth.password.confirm_hint': 'Repeat your password',
  'auth.password.show': 'Show password',
  'auth.password.hide': 'Hide password',
  'auth.remember_me': 'Remember me',
  'auth.sign_in': 'Sign In',
  'auth.sign_in_google': 'Sign in with Google',
  'auth.register.top': 'Join CERD Community',
  'auth.register.title': 'Create Account',
  'auth.register.subtitle':
      'Create your CERD account to request help or support people nearby.',
  'auth.full_name.label': 'Full Name',
  'auth.full_name.hint': 'Your full name',
  'auth.forgot_password': 'Forgot Password?',
  'auth.no_account': "Don't have an account? ",
  'auth.sign_up': 'Sign Up',
  'auth.have_account': 'Already have an account? ',
  'auth.password.requirements': 'Password Requirements',
  'auth.password.req.characters': 'At least 8 characters',
  'auth.password.req.uppercase': 'At least one uppercase letter',
  'auth.password.req.lowercase': 'At least one lowercase letter',
  'auth.password.req.number': 'At least one number',

  // ── Onboarding ─────────────────────────────────────────────────────
  'onboarding.badge.sos': 'SOS',
  'onboarding.badge.live': 'Live',
  'onboarding.badge.team': 'Team',
  'onboarding.badge.alert': 'Alert',
  'onboarding.badge.ready': 'Ready',
  'onboarding.badge.trusted': 'Trusted',
  'onboarding.skip': 'Skip to App',
  'onboarding.get_started': 'Get Started',
  'onboarding.page1.title': 'Help When You Need It',
  'onboarding.page1.description':
      'Report emergencies or community tasks in real-time. Our volunteers respond instantly to help you stay safe and supported.',
  'onboarding.page2.title': 'Live Map Tracking',
  'onboarding.page2.description':
      'See volunteers nearby on a live map. Track their location, get real-time updates, and connect with help faster than ever.',
  'onboarding.page3.title': 'Join Your Community',
  'onboarding.page3.description':
      'Connect with volunteers in your area. Build trust, share experiences, and be part of a caring community that helps each other.',
  'onboarding.page4.title': 'Smart Alerts',
  'onboarding.page4.description':
      'Get instant notifications when volunteers respond. Never miss important updates. Stay informed, stay safe, stay connected.',
  'onboarding.page5.title': 'Ready to Help?',
  'onboarding.page5.description':
      'Join thousands of volunteers making a difference. Whether you need help or want to help others, we\'re here for you.',

  // ── Request Home ───────────────────────────────────────────────────
  'request.home.title': 'Request Home',
  'request.home.subtitle': 'Nearby volunteers and emergency help',
  'request.home.nearby': 'Nearby Active Volunteers',
  'request.home.nearby.empty': 'No active volunteers nearby right now.',
  'request.home.active_requests': 'My Active Requests',
  'request.home.sending_sos': 'Sending SOS',
  'request.home.sos': 'SOS Emergency',
  'request.home.chat_volunteer': 'Chat volunteer',

  // ── Volunteer Home ─────────────────────────────────────────────────
  'volunteer.home.completed': 'Completed',
  'volunteer.home.alerts': 'Alerts',
  'volunteer.home.resolving_area': 'Resolving nearby area...',
  'volunteer.home.nearby_requests': 'Nearby Requests',
  'volunteer.home.view_all': 'View All',
  'volunteer.home.no_requests':
      'No nearby requests yet. Check back in a moment.',
  'volunteer.home.need_help': 'Need help too?',
  'volunteer.home.switch_request': 'Switch to request side and ask for help.',
  'volunteer.home.situation_photos': 'Situation photos',

  // ── Chat ───────────────────────────────────────────────────────────
  'chat.typing': 'typing...',
  'chat.direct_conversation': 'Direct conversation',
  'chat.no_messages': 'No messages yet',
  'chat.message_hint': 'Message...',

  // ── Communities ────────────────────────────────────────────────────
  'communities.title': 'Community',
  'communities.subtitle': 'Volunteer groups and local tasks',
  'communities.filter_all': 'All',
  'communities.no_requests': 'No community requests',
  'communities.no_requests_hint': 'There are no community requests here yet. Pull down or tap retry to check again.',
  'communities.create_title': 'Title',
  'communities.create_details': 'Details',
  'communities.create_category': 'Category',
  'communities.create_time': 'Time needed',
  'communities.create_location': 'Location name',
  'communities.create_people': 'People required',
  'communities.message_hint': 'Message',

  // ── Alerts ─────────────────────────────────────────────────────────
  'alerts.title': 'Alerts',
  'alerts.subtitle': 'Live safety updates near you',
  'alerts.no_recent': 'No recent alerts',
  'alerts.no_recent_hint': 'Safety alerts near you will appear here. Tap retry to check again.',
  'alerts.create_title': 'Title',
  'alerts.create_description': 'Description',
  'alerts.create_location': 'Location name',
  'alerts.send_alert': 'Send Alert',

  // ── Coordination ──────────────────────────────────────────────────
  'coordination.title': 'Coordination',
  'coordination.subtitle': 'Contacts and active support chats',
  'coordination.search_contacts': 'Search contacts...',
  'coordination.tab_requestees': 'Requestees',
  'coordination.tab_volunteers': 'Volunteers',
  'coordination.no_volunteer_chat': 'No accepted volunteer chat yet',
  'coordination.no_contacts': 'No coordination contacts yet',

  // ── Admin Panel ────────────────────────────────────────────────────
  'admin.title': 'Admin Panel',
  'admin.subtitle': 'Review volunteer applications',
  'admin.search_hint': 'Search name, email, CNIC, city',
  'admin.no_name': 'No Name',
  'admin.no_expertise': 'No expertise provided',
  'admin.email_not_available': 'Email not available',
  'admin.no_applications': 'No @status Applications',
  'admin.pull_refresh': 'Pull down to refresh or switch status.',
  'admin.volunteer_review': 'Volunteer Review',
  'admin.verification_docs': 'Verification Documents',
  'admin.cnic_front': 'CNIC Front',
  'admin.cnic_back': 'CNIC Back',
  'admin.doc_not_available': 'Document not available',

  // ── Volunteer Verification ─────────────────────────────────────────
  'verification.title': 'Volunteer Verification',
  'verification.approved_toast': 'Your application has been approved. Please log in again to refresh your volunteer access.',
  'verification.rejected_toast': 'Your application was not approved. Please try again later or contact support.',
  'verification.subtitle': 'Submit your details for admin review',
  'verification.submit_btn': 'Submit for Verification',
  'verification.intro_title': 'Verify your identity',
  'verification.intro_description':
      'Upload CNIC front/back, add your current location, and submit for admin review.',
  'verification.section_account': 'Account',
  'verification.section_account_sub':
      'This email is attached to your login session.',
  'verification.account_email': 'Account Email',
  'verification.no_email': 'No email found',
  'verification.section_identity': 'Identity Documents',
  'verification.section_identity_sub':
      'CNIC front and back are required. Profile photo is optional.',
  'verification.cnic_front_label': 'CNIC Front',
  'verification.cnic_front_helper':
      'Upload a clear front-side image of your national ID card.',
  'verification.cnic_back_label': 'CNIC Back',
  'verification.cnic_back_helper':
      'Upload the back-side image so admin can verify the document properly.',
  'verification.profile_photo_label': 'Profile Photo',
  'verification.profile_photo_helper':
      'Optional. If added, it will appear as your volunteer profile avatar.',
  'verification.upload_progress': '@count/2 required CNIC images selected',
  'verification.section_personal': 'Personal Details',
  'verification.section_personal_sub':
      'Use the same details that appear on your verification documents.',
  'verification.full_name': 'Full Name',
  'verification.full_name_hint': 'Enter your full name',
  'verification.expertise': 'Area of Expertise',
  'verification.expertise_hint': 'Medical, Search & Rescue, Logistics',
  'verification.cnic_number': 'CNIC Number',
  'verification.cnic_hint': 'XXXXX-XXXXXXX-X',
  'verification.section_location': 'Live Location',
  'verification.section_location_sub':
      'Add your current area so admin can verify availability and nearby response coverage.',
  'verification.detecting_location': 'Detecting location...',
  'verification.update_location': 'Update Current Location',
  'verification.use_location': 'Use Current Location',
  'verification.gps_attached': 'GPS attached',
  'verification.city': 'City',
  'verification.city_hint': 'Enter your city',
  'verification.location_address': 'Location / Address',
  'verification.location_hint': 'Enter your detailed location',
  'verification.section_motivation': 'Motivation',
  'verification.section_motivation_sub':
      'Briefly explain your skills and how you can support people.',
  'verification.why_volunteer': 'Why do you want to volunteer?',
  'verification.why_volunteer_hint':
      'Share your motivation and how you can help.',

  // ── Waiting Screen ─────────────────────────────────────────────────
  'waiting.title_pending': 'Awaiting Admin Approval',
  'waiting.title_approved': 'Application Approved! ✅',
  'waiting.title_rejected': 'Application Rejected ❌',
  'waiting.subtitle_pending':
      'Your account is being reviewed.\nWe\'ll notify you shortly.',
  'waiting.subtitle_approved':
      'Welcome to our community!\nRedirecting to home...',
  'waiting.subtitle_rejected': 'Please try again later or contact support.',

  // ── Request Help Sheet ─────────────────────────────────────────────
  'request_help.title': 'Request Help',
  'request_help.subtitle':
      'Describe your situation and we will connect you with helpers.',
  'request_help.category': 'Category',
  'request_help.category_hint': 'Select category',
  'request_help.subcategory': 'Subcategory',
  'request_help.subcategory_hint': 'Select subcategory',
  'request_help.description': 'Description',
  'request_help.photos': 'Photos',
  'request_help.send_request': 'Send Request',

  // ── Profile ────────────────────────────────────────────────────────
  'profile.title': 'Profile',
  'profile.subtitle': 'Account, role, and preferences',
  'profile.status': 'Status',
  'profile.location': 'Location',
  'profile.rating': 'Rating',
  'profile.account_details': 'Account Details',
  'profile.full_name': 'Full name',
  'profile.email': 'Email',
  'profile.use_current': 'Use Current',
  'profile.quick_actions': 'Quick Actions',
  'profile.volunteer_home': 'Volunteer Home',
  'profile.request_home': 'Request Home',
  'profile.communities': 'Communities',
  'profile.dark_mode': 'Dark mode',
  'profile.privacy': 'Privacy',
  'profile.data_permissions': 'Data and permissions',
  'profile.data_permissions.intro':
      'Here is what the app stores on your device and on our servers, and what each permission is used for.',
  'profile.session_access': 'Stay signed in',
  'profile.session_access.text':
      'Remain logged in so you don\u2019t have to sign in every time. Signing out clears your session.',
  'profile.location_use': 'Location',
  'profile.location_use.text':
      'Allow the app to use your location so nearby requests and emergencies work correctly. It is never shared publicly.',
  'profile.notifications': 'Notifications',
  'profile.notifications.text':
      'Receive SOS alerts and important updates while the app is open.',
  'profile.preferences': 'App settings',
  'profile.preferences.text':
      'Your language and appearance choices are saved on this device only.',
  'profile.sign_out': 'Sign out',

  // ── Admin info row labels ─────────────────────────────────────────
  'admin.label_name': 'Name',
  'admin.label_email': 'Email',
  'admin.label_phone': 'Phone',
  'admin.label_city': 'City',
  'admin.label_location': 'Location',
  'admin.label_gps': 'GPS',
  'admin.label_expertise': 'Expertise',
  'admin.label_cnic': 'CNIC',
  'admin.label_reason': 'Reason',
  'admin.not_provided': 'Not provided',
  'admin.phone_not_provided': 'Not provided',
  'admin.not_available': 'Not available',
  'admin.volunteer_approved': 'Volunteer approved.',
  'admin.volunteer_rejected': 'Volunteer rejected.',
  'alerts.fill_required': 'Please fill alert title, description, and location.',
  'alerts.sent': 'Alert sent.',
  'auth.error.confirm_password': 'Please confirm your password',
  'auth.error.fix_errors': 'Please fix the errors above',
  'auth.error.google_failed': 'Google sign-in failed',
  'auth.error.passwords_mismatch': 'Passwords do not match',
  'auth.success.google': 'Google sign-in successful!',
  'auth.success.login': 'Login successful!',
  'auth.success.register': 'Account created successfully!',
  'auth.volunteer.approved_relogin':
      'Your volunteer approval is ready. Please log in again.',
  'common.done': 'Done',
  'common.helpline': 'Helpline',
  'common.later': 'Later',
  'common.submit': 'Submit',
  'community.form.cat_accident': 'Accident',
  'community.form.cat_medical': 'Medical',
  'community.form.cat_natural_disaster': 'Natural Disaster',
  'community.form.cat_other': 'Other',
  'community.form.cat_shelter': 'Shelter',
  'community.form.complete_fields':
      'Please complete all community fields.',
  'community.form.deleted': 'Community deleted.',
  'community.form.joined': 'Joined community.',
  'community.form.only_volunteers':
      'Only volunteers can create communities.',
  'community.form.published': 'Community published.',
  'community.form.started': 'Community started.',
  'map.cancelling': 'Cancelling',
  'map.chat_unavailable': 'Chat is not available for this request.',
  'map.completing': 'Completing',
  'map.distance_away': '{{distance}} distance away',
  'map.done': 'Done',
  'map.filter_users': 'Users',
  'map.navigate': 'Navigate',
  'map.no_active_cancel': 'No active request to cancel.',
  'map.no_active_complete': 'No active request to complete.',
  'map.permission_message':
      'Location permission is required to refresh the map.',
  'map.request_cancelled': 'Request cancelled.',
  'map.request_completed': 'Request completed.',
  'map.requestee_fallback': 'Requestee',
  'map.status_people': '{{count}} nearby people',
  'map.status_users': '{{count}} nearby users',
  'map.status_volunteers': '{{count}} nearby volunteers',
  'map.subtitle': 'Nearby volunteers and live position',
  'map.title': 'Emergency Map',
  'map.tracking_ended': 'Tracking ended',
  'map.tracking_started': 'Live tracking started',
  'profile.fallback_location': 'Location not set',
  'profile.fallback_name': 'Community Member',
  'profile.finding': 'Finding...',
  'profile.location_failed': 'Could not resolve your location name.',
  'profile.location_updated': 'Location updated.',
  'profile.name_required': 'Name is required.',
  'profile.role.member': 'Community member',
  'profile.role.requestee': 'Requestee',
  'profile.role.volunteer': 'Volunteer',
  'profile.status_not_submitted': 'Verification not submitted',
  'profile.updated': 'Profile updated.',
  'profile.warning_communities':
      'Communities are available for volunteers.',
  'request.card.emergency': 'EMERGENCY',
  'request.card.no_description': 'No description provided.',
  'request.form.add': 'Add',
  'request.form.add_photos': 'Add situation photos',
  'request.form.description_hint': 'Describe your situation...',
  'request.form.photo_limit': 'Up to 2 images, 5MB each',
  'request.form.photo_progress': '{{count}}/2 situation photos',
  'sos.already_active': 'You already have an active SOS.',
  'sos.call_helpline': 'Call Helpline',
  'sos.cancel': 'Cancel SOS',
  'sos.cancel.confirm': 'Yes, Cancel',
  'sos.cancel.keep': 'Keep SOS',
  'sos.cancel.message':
      'Cancelling will notify volunteers that help is no longer needed.',
  'sos.cancel.title': 'Cancel SOS?',
  'sos.chat_not_accepted':
      'A volunteer has not accepted this request yet.',
  'sos.escalated':
      'No volunteer accepted yet. SOS escalated to a wider area.',
  'sos.escalated_radius':
      'No volunteer accepted yet. SOS widened to {{radius}} km after {{minutes}} minutes.',
  'sos.helplines.title': 'Emergency Helplines',
  'sos.not_volunteer':
      'You are not eligible because you are not a volunteer.',
  'sos.rating.title': 'Rate volunteer',
  'sos.rating_comment': 'Comment optional',
  'sos.rating_submitted': 'Rating submitted.',
  'sos.sent.message':
      'Your SOS was sent to nearby volunteers. Call a helpline if you need immediate support.',
  'sos.sent.message_count':
      'Your SOS was sent to {{count}} nearby volunteer(s). Call a helpline if you need immediate support.',
  'sos.sent.title': 'SOS Sent',
  'sos.snooze': 'Snooze',
  'sos.snooze.option': 'Snooze {{min}}',
  'sos.snooze.pause_hint': 'Pause the ringing and vibration',
  'sos.snooze.paused': 'Ringing paused — {{time}}',
  'sos.snooze.recommended': 'Recommended',
  'sos.snooze.resume': 'Resume',
  'sos.snooze.title': 'Snooze SOS alerts',
  'sos.status.active': 'SOS ACTIVE',
  'sos.status.notified': 'Nearby volunteers notified',
  'sos.status.notified_count': '{{count}} nearby volunteer(s) notified',
  'sos.tracking.view_map': 'View Map',
  'splash.brand': 'CERD Community',
  'splash.tagline': 'Community support when it matters',
  'splash.status.preparing': 'Preparing CERD Community...',
  'splash.status.loading_profile': 'Loading your profile...',
  'splash.status.checking_verification':
      'Checking your verification status...',
  'splash.status.opening_dashboard':
      'Opening your volunteer dashboard...',
  'tracking.arrived': 'Volunteer Arrived',
  'tracking.distance': 'Distance',
  'tracking.eta': 'ETA',
  'tracking.live': 'Live Tracking',
  'tracking.no_session': 'No active tracking session',
  'tracking.status': 'Status',
  'tracking.status_arrived': 'Arrived',
  'tracking.status_enroute': 'En Route',
  'tracking.status_waiting': 'Waiting',
  'update.available': 'Update Available',
  'update.cancelled': 'Download cancelled. You can update later.',
  'update.connecting': 'Connecting…',
  'update.downloading': 'Downloading update',
  'update.downloading_hint':
      'A smaller package that matches this phone is being downloaded.',
  'update.incomplete': 'Download looks incomplete. Please try again later.',
  'update.installer_failed':
      'Installer could not open ({{message}}). Please install the APK manually.',
  'update.missing_link': 'Download link is missing.',
  'update.now': 'Update Now',
  'update.required': 'Update required',
  'update.required_message':
      'A newer version of the app is needed. Update to keep using the latest fixes.',
  'update.version_ready': 'Version {{version}} is ready',
  'update.whats_new': "What's new:",
  'verification.cnic_format_hint': 'Format: XXXXX-XXXXXXX-X',
  'verification.complete_profile': 'Complete Your Profile',
  'verification.selected_image': 'Selected image',
  'verification.tap_to_upload': 'Tap to upload',
  'verification.tap_to_upload_photo': 'Tap to upload photo',
  'verification.upload_hint': 'JPG or PNG up to 5MB',
  'verification.upload_hint_photo': 'PNG, JPG up to 5MB',
  'volunteer.home.accept_navigate': 'Accept & Navigate',
  'volunteer.home.cannot_accept_own': 'You cannot accept your own request.',
  'volunteer.home.default_name': 'Volunteer User',
  'volunteer.home.request_unavailable': 'Request is not available right now.',
  'volunteer.home.sos_intro': 'A nearby person needs urgent help. Respond now.',
  'toast.server_error': 'Something went wrong. Please try again later.',
  'toast.network_error': 'Network error. Please check your connection.',
  'toast.timeout_error': 'The request took too long. Please try again.',
  'toast.invalid_input': 'Please check your input and try again.',
  'toast.session_expired': 'Your session has expired. Please sign in again.',
  'toast.not_found': 'We could not find what you were looking for.',
  'toast.conflict': 'This action conflicts with something that already exists. Please try something else.',
};
