const Map<String, String> urPK = {
  // ── Common ─────────────────────────────────────────────────────────
  'common.back': 'واپس',
  'common.home': 'ہوم',
  'common.map': 'نقشہ',
  'common.community': 'کمیونٹی',
  'common.profile': 'پروفائل',
  'common.alerts': 'الرٹس',
  'common.help': 'مدد',
  'common.coordination': 'رابطہ',
  'common.next': 'اگلا',
  'common.save': 'محفوظ کریں',
  'common.saving': 'محفوظ ہو رہا ہے',
  'common.got_it': 'ٹھیک ہے',
  'common.retry': 'دوبارہ کوشش کریں',
  'common.rating': 'ریٹنگ',
  'common.ratings': 'ریٹنگز',
  'common.active': 'فعال',
  'common.cancel': 'منسوخ کریں',
  'common.accept': 'قبول کریں',
  'common.accepting': 'قبول کیا جا رہا ہے',
  'common.call': 'کال کریں',
  'common.urgent': 'فوری',
  'common.reject': 'مسترد کریں',
  'common.approve': 'منظور کریں',
  'common.delete': 'حذف کریں',
  'common.start': 'شروع کریں',
  'common.join': 'شامل ہوں',
  'common.chat': 'چیٹ',
  'common.message': 'پیغام',
  'common.send': 'بھیجیں',
  'common.publish': 'شائع کریں',
  'common.publishing': 'شائع ہو رہا ہے...',
  'common.sending': 'بھیجا جا رہا ہے...',
  'common.search': 'تلاش کریں',
  'common.improve': 'بہتر بنائیں',
  'common.not_provided': 'فراہم نہیں کیا گیا',
  'common.not_available': 'دستیاب نہیں',
  'common.pending': 'زیرِ التواء',
  'common.approved': 'منظور شدہ',
  'common.rejected': 'مسترد شدہ',

  // ── Language ───────────────────────────────────────────────────────
  'language.label': 'زبان',
  'language.en': 'EN',
  'language.ur': 'اردو',
  'language.choose': 'زبان منتخب کریں',

  // ── Role Selection ─────────────────────────────────────────────────
  'role.selection.title': 'میں چاہتا/چاہتی ہوں...',
  'role.selection.subtitle': 'اپنی کمیونٹی کی مدد کرنے کا طریقہ منتخب کریں',
  'role.request_help.title': 'مدد طلب کریں',
  'role.request_help.description':
      'اپنے علاقے کے رضاکاروں سے\nمدد کے لیے درخواست بھیجیں',
  'role.volunteer.title': 'رضاکار کی تصدیق کریں',
  'role.volunteer.description':
      'اپنے علاقے کی مدد کی درخواستیں\nدیکھیں اور جواب دیں',

  // ── Auth ───────────────────────────────────────────────────────────
  'auth.login.welcome': 'خوش آمدید',
  'auth.login.subtitle': 'اپنی کمیونٹی کی مدد جاری رکھنے کے لیے سائن اِن کریں۔',
  'auth.email.label': 'ای میل',
  'auth.email.hint': 'example@email.com',
  'auth.password.label': 'پاس ورڈ',
  'auth.password.hint': 'اپنا پاس ورڈ درج کریں',
  'auth.password.create_hint': 'نیا پاس ورڈ بنائیں',
  'auth.password.confirm_label': 'پاس ورڈ کی تصدیق',
  'auth.password.confirm_hint': 'اپنا پاس ورڈ دوبارہ لکھیں',
  'auth.password.show': 'پاس ورڈ دکھائیں',
  'auth.password.hide': 'پاس ورڈ چھپائیں',
  'auth.remember_me': 'مجھے یاد رکھیں',
  'auth.sign_in': 'سائن اِن',
  'auth.sign_in_google': 'Google کے ساتھ سائن اِن کریں',
  'auth.register.top': 'Join CERD Community',
  'auth.register.title': 'اکاؤنٹ بنائیں',
  'auth.register.subtitle':
      'مدد لینے یا قریب موجود افراد کی مدد کے لیے اپنا CERD اکاؤنٹ بنائیں۔',
  'auth.full_name.label': 'پورا نام',
  'auth.full_name.hint': 'اپنا پورا نام',
  'auth.forgot_password': 'پاسورڈ بھول گئے؟',
  'auth.no_account': 'کیا اکاؤنٹ نہیں ہے؟ ',
  'auth.sign_up': 'سائن اپ کریں',
  'auth.have_account': 'پہلے سے اکاؤنٹ ہے؟ ',
  'auth.password.requirements': 'پاسورڈ کی ضروریات',
  'auth.password.req.characters': 'کم از کم 8 حروف',
  'auth.password.req.uppercase': 'کم از کم ایک بڑا حرف (A-Z)',
  'auth.password.req.lowercase': 'کم از کم ایک چھوٹا حرف (a-z)',
  'auth.password.req.number': 'کم از کم ایک ہندسہ (0-9)',

  // ── Onboarding ─────────────────────────────────────────────────────
  'onboarding.badge.sos': 'SOS',
  'onboarding.badge.live': 'لائیو',
  'onboarding.badge.team': 'ٹیم',
  'onboarding.badge.alert': 'الرٹ',
  'onboarding.badge.ready': 'تیار',
  'onboarding.badge.trusted': 'قابلِ اعتماد',
  'onboarding.skip': 'ایپ پر جائیں',
  'onboarding.get_started': 'شروع کریں',
  'onboarding.page1.title': 'جب ضرورت ہو مدد پائیں',
  'onboarding.page1.description':
      'ہنگامی صورتحال یا کمیونٹی کام فوری رپورٹ کریں۔ ہمارے رضاکار فوراً جواب دیتے ہیں تاکہ آپ محفوظ اور باخبر رہیں۔',
  'onboarding.page2.title': 'لائیو میپ ٹریکنگ',
  'onboarding.page2.description':
      'اپنے قریب رضاکاروں کو لائیو نقشے پر دیکھیں۔ مقام اور اپڈیٹس کے ساتھ تیز رفتار مدد حاصل کریں۔',
  'onboarding.page3.title': 'اپنی کمیونٹی سے جڑیں',
  'onboarding.page3.description':
      'اپنے علاقے کے رضاکاروں سے رابطہ کریں، اعتماد قائم کریں اور ایک دوسرے کی مدد کرنے والی کمیونٹی کا حصہ بنیں۔',
  'onboarding.page4.title': 'سمارٹ الرٹس',
  'onboarding.page4.description':
      'جب رضاکار جواب دیں تو فوری نوٹیفکیشن حاصل کریں۔ اہم اپڈیٹس کبھی مس نہ کریں۔',
  'onboarding.page5.title': 'مدد کے لیے تیار ہیں؟',
  'onboarding.page5.description':
      'ہزاروں رضاکاروں کے ساتھ شامل ہوں۔ آپ کو مدد چاہیے یا آپ مدد کرنا چاہتے ہیں، ہم آپ کے ساتھ ہیں۔',

  // ── Request Home ───────────────────────────────────────────────────
  'request.home.title': 'درخواست ہوم',
  'request.home.subtitle': 'قریب موجود رضاکار اور ہنگامی مدد',
  'request.home.nearby': 'قریب موجود فعال رضاکار',
  'request.home.nearby.empty': 'اس وقت قریب کوئی فعال رضاکار موجود نہیں۔',
  'request.home.active_requests': 'میری فعال درخواستیں',
  'request.home.sending_sos': 'SOS بھیجا جا رہا ہے',
  'request.home.sos': 'SOS ایمرجنسی',
  'request.home.chat_volunteer': 'رضاکار سے چیٹ',

  // ── Volunteer Home ─────────────────────────────────────────────────
  'volunteer.home.completed': 'مکمل',
  'volunteer.home.alerts': 'الرٹس',
  'volunteer.home.resolving_area': 'قریبی علاقہ تلاش کیا جا رہا ہے...',
  'volunteer.home.nearby_requests': 'قریبی مدد کی درخواستیں',
  'volunteer.home.view_all': 'سب دیکھیں',
  'volunteer.home.no_requests':
      'ابھی تک کوئی قریبی درخواست نہیں ہے۔ کچھ دیر بعد دوبارہ چیک کریں۔',
  'volunteer.home.need_help': 'کیا آپ کو بھی مدد کی ضرورت ہے؟',
  'volunteer.home.switch_request':
      'درخواست گزار کی طرف جائیں اور مدد طلب کریں۔',
  'volunteer.home.situation_photos': 'صورتحال کی تصاویر',

  // ── Chat ───────────────────────────────────────────────────────────
  'chat.typing': 'ٹائپنگ ہو رہی ہے...',
  'chat.direct_conversation': 'براہ راست بات چیت',
  'chat.no_messages': 'ابھی تک کوئی پیغامات نہیں ہیں',
  'chat.message_hint': 'پیغام لکھیں...',

  // ── Communities ────────────────────────────────────────────────────
  'communities.title': 'کمیونٹی',
  'communities.subtitle': 'رضاکار گروپس اور مقامی کام',
  'communities.filter_all': 'سب',
  'communities.no_requests': 'کوئی کمیونٹی درخواستیں نہیں ہیں',
  'communities.no_requests_hint': 'یہاں ابھی کوئی کمیونٹی درخواست نہیں ہے۔ دوبارہ چیک کرنے کے لیے نیچے کھینچیں یا دوبارہ کوشش پر ٹیپ کریں۔',
  'communities.create_title': 'عنوان',
  'communities.create_details': 'تفصیلات',
  'communities.create_category': 'زمرہ',
  'communities.create_time': 'درکار وقت',
  'communities.create_location': 'مقام کا نام',
  'communities.create_people': 'درکار افراد کی تعداد',
  'communities.message_hint': 'پیغام',

  // ── Alerts ─────────────────────────────────────────────────────────
  'alerts.title': 'الرٹس',
  'alerts.subtitle': 'آپ کے قریب لائیو حفاظتی اپ ڈیٹس',
  'alerts.no_recent': 'کوئی حالیہ الرٹ نہیں ہے',
  'alerts.no_recent_hint': 'آپ کے قریب حفاظتی الرٹس یہاں ظاہر ہوں گے۔ دوبارہ چیک کرنے کے لیے دوبارہ کوشش پر ٹیپ کریں۔',
  'alerts.create_title': 'عنوان',
  'alerts.create_description': 'تفصیل',
  'alerts.create_location': 'مقام کا نام',
  'alerts.send_alert': 'الرٹ بھیجیں',

  // ── Coordination ──────────────────────────────────────────────────
  'coordination.title': 'رابطہ کاری',
  'coordination.subtitle': 'رابطے اور فعال معاونت چیٹس',
  'coordination.search_contacts': 'رابطے تلاش کریں...',
  'coordination.tab_requestees': 'درخواست گزار',
  'coordination.tab_volunteers': 'رضاکار',
  'coordination.no_volunteer_chat': 'ابھی تک کوئی منظور شدہ رضاکار چیٹ نہیں ہے',
  'coordination.no_contacts': 'ابھی تک کوئی رابطہ کاری رابطے نہیں ہیں',

  // ── Admin Panel ────────────────────────────────────────────────────
  'admin.title': 'ایڈمن پینل',
  'admin.subtitle': 'رضاکارانہ درخواستوں کا جائزہ لیں',
  'admin.search_hint': 'نام، ای میل، شناختی کارڈ، شہر تلاش کریں',
  'admin.no_name': 'کوئی نام نہیں',
  'admin.no_expertise': 'مہارت فراہم نہیں کی گئی',
  'admin.email_not_available': 'ای میل دستیاب نہیں',
  'admin.no_applications': 'کوئی @status درخواستیں نہیں ہیں',
  'admin.pull_refresh': 'تازہ کاری کے لیے نیچے کھینچیں یا اسٹیٹس تبدیل کریں۔',
  'admin.volunteer_review': 'رضاکار جائزہ',
  'admin.verification_docs': 'تصدیقی دستاویزات',
  'admin.cnic_front': 'شناختی کارڈ سامنے والا حصہ',
  'admin.cnic_back': 'شناختی کارڈ پیچھے والا حصہ',
  'admin.doc_not_available': 'دستاویز دستیاب نہیں ہے',

  // ── Volunteer Verification ─────────────────────────────────────────
  'verification.title': 'رضاکارانہ تصدیق',
  'verification.approved_toast': 'آپ کی درخواست منظور ہو گئی ہے۔ رضاکار رسائی حاصل کرنے کے لیے براہ کرم دوبارہ لاگ ان کریں۔',
  'verification.rejected_toast': 'آپ کی درخواست منظور نہیں ہوئی۔ براہ کرم بعد میں دوبارہ کوشش کریں یا سپورٹ سے رابطہ کریں۔',
  'verification.subtitle': 'ایڈمن کے جائزے کے لیے اپنی تفصیلات جمع کروائیں',
  'verification.submit_btn': 'تصدیق کے لیے جمع کروائیں',
  'verification.intro_title': 'اپنی شناخت کی تصدیق کریں',
  'verification.intro_description':
      'اپنے شناختی کارڈ کے سامنے اور پیچھے والے حصے کی تصاویر اپ لوڈ کریں، موجودہ مقام شامل کریں اور ایڈمن کے جائزے کے لیے جمع کروائیں۔',
  'verification.section_account': 'اکاؤنٹ',
  'verification.section_account_sub':
      'یہ ای میل آپ کے لاگ ان سیشن سے منسلک ہے۔',
  'verification.account_email': 'اکاؤنٹ ای ای میل',
  'verification.no_email': 'کوئی ای میل نہیں ملا',
  'verification.section_identity': 'شناختی دستاویزات',
  'verification.section_identity_sub':
      'شناختی کارڈ کا سامنے اور پیچھے والا حصہ لازمی ہے۔ پروفائل تصویر اختیاری ہے۔',
  'verification.cnic_front_label': 'شناختی کارڈ سامنے والا حصہ',
  'verification.cnic_front_helper':
      'اپنے قومی شناختی کارڈ کے سامنے والے حصے کی واضح تصویر اپ لوڈ کریں۔',
  'verification.cnic_back_label': 'شناختی کارڈ پیچھے والا حصہ',
  'verification.cnic_back_helper':
      'پچھلے حصے کی تصویر اپ لوڈ کریں تاکہ ایڈمن دستاویز کی صحیح تصدیق کر سکے۔',
  'verification.profile_photo_label': 'پروفائل تصویر',
  'verification.profile_photo_helper':
      'اختیاری۔ اگر شامل کی جائے تو یہ آپ کی رضاکار پروفائل اوتار کے طور پر ظاہر ہوگی۔',
  'verification.upload_progress':
      '@count/2 مطلوبہ شناختی کارڈ تصاویر منتخب کی گئیں',
  'verification.section_personal': 'ذاتی معلومات',
  'verification.section_personal_sub':
      'وہی تفصیلات استعمال کریں جو آپ کے تصدیقی دستاویزات پر ظاہر ہوتی ہیں۔',
  'verification.full_name': 'پورا نام',
  'verification.full_name_hint': 'اپنا پورا نام درج کریں',
  'verification.expertise': 'مہارت کا شعبہ',
  'verification.expertise_hint': 'طبی، تلاش اور بچاؤ، لاجسٹکس',
  'verification.cnic_number': 'شناختی کارڈ نمبر',
  'verification.cnic_hint': 'XXXXX-XXXXXXX-X',
  'verification.section_location': 'لائیو مقام',
  'verification.section_location_sub':
      'اپنا موجودہ علاقہ شامل کریں تاکہ ایڈمن دستیابی اور قریبی رسائی کی تصدیق کر سکے۔',
  'verification.detecting_location': 'مقام کا پتہ لگایا جا رہا ہے...',
  'verification.update_location': 'موجودہ مقام اپ ڈیٹ کریں',
  'verification.use_location': 'موجودہ مقام استعمال کریں',
  'verification.gps_attached': 'جی پی ایس منسلک ہے',
  'verification.city': 'شہر',
  'verification.city_hint': 'اپنا شہر درج کریں',
  'verification.location_address': 'مقام / پتہ',
  'verification.location_hint': 'اپنا تفصیلی پتہ درج کریں',
  'verification.section_motivation': 'حوصلہ افزائی / وجہ',
  'verification.section_motivation_sub':
      'مختصراً بتائیں کہ آپ کے پاس کیا مہارتیں ہیں اور آپ لوگوں کی کس طرح مدد کر سکتے ہیں۔',
  'verification.why_volunteer': 'آپ کیوں رضاکار بننا چاہتے ہیں؟',
  'verification.why_volunteer_hint':
      'اپنی وجہ بتائیں کہ آپ کس طرح مدد کر سکتے ہیں۔',

  // ── Waiting Screen ─────────────────────────────────────────────────
  'waiting.title_pending': 'ایڈمن کی منظوری کا انتظار ہے',
  'waiting.title_approved': 'درخواست منظور ہو گئی! ✅',
  'waiting.title_rejected': 'درخواست مسترد ہو گئی ❌',
  'waiting.subtitle_pending':
      'آپ کے اکاؤنٹ کا جائزہ لیا جا رہا ہے۔\nہم جلد ہی آپ کو مطلع کریں گے۔',
  'waiting.subtitle_approved':
      'ہماری کمیونٹی میں خوش آمدید!\nہوم پیج پر بھیجا جا رہا ہے...',
  'waiting.subtitle_rejected':
      'براہ کرم بعد میں دوبارہ کوشش کریں یا سپورٹ سے رابطہ کریں۔',

  // ── Request Help Sheet ─────────────────────────────────────────────
  'request_help.title': 'مدد کی درخواست',
  'request_help.subtitle':
      'اپنی صورتحال بیان کریں اور ہم آپ کو مدد گاروں سے جوڑیں گے۔',
  'request_help.category': 'زمرہ',
  'request_help.category_hint': 'زمرہ منتخب کریں',
  'request_help.subcategory': 'ذیلی زمرہ',
  'request_help.subcategory_hint': 'ذیلی زمرہ منتخب کریں',
  'request_help.description': 'تفصیل',
  'request_help.photos': 'تصاویر',
  'request_help.send_request': 'درخواست بھیجیں',

  // ── Profile ────────────────────────────────────────────────────────
  'profile.title': 'پروفائل',
  'profile.subtitle': 'اکاؤنٹ، کردار اور ترجیحات',
  'profile.status': 'حیثیت',
  'profile.location': 'مقام',
  'profile.rating': 'ریٹنگ',
  'profile.account_details': 'اکاؤنٹ کی تفصیلات',
  'profile.full_name': 'پورا نام',
  'profile.email': 'ای میل',
  'profile.use_current': 'موجودہ مقام استعمال کریں',
  'profile.quick_actions': 'فوری اقدامات',
  'profile.volunteer_home': 'رضاکار ہوم',
  'profile.request_home': 'درخواست ہوم',
  'profile.communities': 'کمیونٹیز',
  'profile.dark_mode': 'ڈارک موڈ',
  'profile.privacy': 'رازداری',
  'profile.data_permissions': 'ڈیٹا اور اجازتیں',
  'profile.data_permissions.intro':
      'یہاں بتایا گیا ہے کہ ایپ آپ کے آلے اور ہمارے سرورز پر کیا محفوظ کرتی ہے، اور ہر اجازت کس کام کے لیے استعمال ہوتی ہے۔',
  'profile.session_access': 'سائن ان رہیں',
  'profile.session_access.text':
      'سائن ان رہیں تاکہ آپ کو ہر بار لاگ ان نہ کرنا پڑے۔ سائن آؤٹ کرنے سے آپ کا سیشن ختم ہو جاتا ہے۔',
  'profile.location_use': 'مقام',
  'profile.location_use.text':
      'ایپ کو اپنا مقام استعمال کرنے کی اجازت دیں تاکہ قریبی درخواستیں اور ہنگامی صورتحال درست طریقے سے کام کریں۔ یہ کبھی عوامی طور پر شیئر نہیں ہوتا۔',
  'profile.notifications': 'اطلاعات',
  'profile.notifications.text':
      'ایپ کھلی ہونے پر SOS الرٹس اور اہم اپ ڈیٹس وصول کریں۔',
  'profile.preferences': 'ایپ کی ترتیبات',
  'profile.preferences.text':
      'آپ کی زبان اور ظاہری شکل کے انتخاب صرف اس آلے پر محفوظ ہوتے ہیں۔',
  'profile.sign_out': 'سائن آؤٹ',

  // ── Admin info row labels ─────────────────────────────────────────
  'admin.label_name': 'نام',
  'admin.label_email': 'ای میل',
  'admin.label_phone': 'فون نمبر',
  'admin.label_city': 'شہر',
  'admin.label_location': 'مقام',
  'admin.label_gps': 'جی پی ایس',
  'admin.label_expertise': 'مہارت',
  'admin.label_cnic': 'شناختی کارڈ نمبر',
  'admin.label_reason': 'وجہ / ترغیب',
  'admin.not_provided': 'فراہم نہیں کیا گیا',
  'admin.phone_not_provided': 'فراہم نہیں کیا گیا',
  'admin.not_available': 'دستیاب نہیں',
  'admin.volunteer_approved': 'رضاکار منظور ہو گیا۔',
  'admin.volunteer_rejected': 'رضاکار مسترد ہو گیا۔',
  'alerts.fill_required': 'براہ کرم الرٹ کا عنوان، تفصیل اور مقام پُر کریں۔',
  'alerts.sent': 'الرٹ بھیج دیا گیا۔',
  'auth.error.confirm_password': 'براہ کرم اپنے پاس ورڈ کی تصدیق کریں',
  'auth.error.fix_errors': 'براہ کرم اوپر دی گئی غلطیوں کو درست کریں',
  'auth.error.google_failed': 'Google سائن اِن ناکام ہوا',
  'auth.error.passwords_mismatch': 'پاس ورڈز آپس میں مماثل نہیں ہیں',
  'auth.success.google': 'Google سائن اِن کامیاب ہوا!',
  'auth.success.login': 'لاگ اِن کامیاب ہوا!',
  'auth.success.register': 'اکاؤنٹ کامیابی سے بن گیا!',
  'auth.volunteer.approved_relogin':
      'آپ کی رضاکارانہ منظوری تیار ہے۔ براہ کرم دوبارہ لاگ اِن کریں۔',
  'common.done': 'مکمل',
  'common.helpline': 'ہیلپ لائن',
  'common.later': 'بعد میں',
  'common.submit': 'جمع کریں',
  'community.form.cat_accident': 'حادثہ',
  'community.form.cat_medical': 'طبی',
  'community.form.cat_natural_disaster': 'قدرتی آفت',
  'community.form.cat_other': 'دیگر',
  'community.form.cat_shelter': 'پناہ',
  'community.form.complete_fields':
      'براہ کرم کمیونٹی کے تمام خانے پُر کریں۔',
  'community.form.deleted': 'کمیونٹی حذف ہو گئی۔',
  'community.form.joined': 'کمیونٹی میں شامل ہو گئے۔',
  'community.form.only_volunteers':
      'صرف رضاکار کمیونٹیز بنا سکتے ہیں۔',
  'community.form.published': 'کمیونٹی شائع ہو گئی۔',
  'community.form.started': 'کمیونٹی شروع ہو گئی۔',
  'map.cancelling': 'منسوخ ہو رہا ہے',
  'map.chat_unavailable': 'اس درخواست کے لیے چیٹ دستیاب نہیں ہے۔',
  'map.completing': 'مکمل ہو رہا ہے',
  'map.distance_away': '{{distance}} دور',
  'map.done': 'مکمل',
  'map.filter_users': 'صارفین',
  'map.navigate': 'نیویگیٹ',
  'map.no_active_cancel': 'منسوخ کرنے کے لیے کوئی فعال درخواست نہیں۔',
  'map.no_active_complete': 'مکمل کرنے کے لیے کوئی فعال درخواست نہیں۔',
  'map.permission_message':
      'نقشہ تازہ کرنے کے لیے لوکیشن کی اجازت درکار ہے۔',
  'map.request_cancelled': 'درخواست منسوخ کر دی گئی۔',
  'map.request_completed': 'درخواست مکمل ہو گئی۔',
  'map.requestee_fallback': 'درخواست گزار',
  'map.status_people': '{{count}} قریبی لوگ',
  'map.status_users': '{{count}} قریبی صارفین',
  'map.status_volunteers': '{{count}} قریبی رضاکار',
  'map.subtitle': 'قریبی رضاکار اور لائیو لوکیشن',
  'map.title': 'ایمرجنسی نقشہ',
  'map.tracking_ended': 'ٹریکنگ ختم ہو گئی',
  'map.tracking_started': 'لائیو ٹریکنگ شروع ہو گئی',
  'profile.fallback_location': 'لوکیشن سیٹ نہیں کی گئی',
  'profile.fallback_name': 'کمیونٹی رکن',
  'profile.finding': 'تلاش ہو رہی ہے...',
  'profile.location_failed': 'آپ کے مقام کا نام معلوم نہیں ہو سکا۔',
  'profile.location_updated': 'لوکیشن اپ ڈیٹ ہو گئی۔',
  'profile.name_required': 'نام درکار ہے۔',
  'profile.role.member': 'کمیونٹی رکن',
  'profile.role.requestee': 'درخواست گزار',
  'profile.role.volunteer': 'رضاکار',
  'profile.status_not_submitted': 'تصدیق جمع نہیں کروائی گئی',
  'profile.updated': 'پروفائل اپ ڈیٹ ہو گئی۔',
  'profile.warning_communities':
      'کمیونٹی سہولت صرف رضاکاروں کے لیے دستیاب ہے۔',
  'request.card.emergency': 'ایمرجنسی',
  'request.card.no_description': 'کوئی تفصیل فراہم نہیں کی گئی۔',
  'request.form.add': 'شامل کریں',
  'request.form.add_photos': 'صورتحال کی تصاویر شامل کریں',
  'request.form.description_hint': 'اپنی صورتحال بیان کریں...',
  'request.form.photo_limit': 'زیادہ سے زیادہ 2 تصاویر، ہر ایک 5MB',
  'request.form.photo_progress': '{{count}}/2 صورتحال کی تصاویر',
  'sos.already_active': 'آپ کے پاس پہلے سے ایک فعال SOS موجود ہے۔',
  'sos.call_helpline': 'ہیلپ لائن پر کال کریں',
  'sos.cancel': 'SOS منسوخ کریں',
  'sos.cancel.confirm': 'ہاں، منسوخ کریں',
  'sos.cancel.keep': 'SOS برقرار رکھیں',
  'sos.cancel.message':
      'منسوخ کرنے سے رضاکاروں کو مطلع کیا جائے گا کہ مدد کی مزید ضرورت نہیں ہے۔',
  'sos.cancel.title': 'SOS منسوخ کریں؟',
  'sos.chat_not_accepted':
      'ابھی تک کسی رضاکار نے اس درخواست کو قبول نہیں کیا۔',
  'sos.escalated':
      'ابھی تک کسی رضاکار نے قبول نہیں کیا۔ SOS کو وسیع تر علاقے میں بھیج دیا گیا۔',
  'sos.escalated_radius':
      'ابھی تک کسی رضاکار نے قبول نہیں کیا۔ SOS کو {{radius}} کلومیٹر تک وسیع کیا گیا ({{minutes}} منٹ بعد)۔',
  'sos.helplines.title': 'ایمرجنسی ہیلپ لائنز',
  'sos.not_volunteer':
      'آپ اہل نہیں ہیں کیونکہ آپ رضاکار نہیں ہیں۔',
  'sos.rating.title': 'رضاکار کو ریٹ کریں',
  'sos.rating_comment': 'تبصرہ (اختیاری)',
  'sos.rating_submitted': 'ریٹنگ جمع کر دی گئی۔',
  'sos.sent.message':
      'آپ کا SOS قریبی رضاکاروں کو بھیج دیا گیا۔ فوری مدد کے لیے ہیلپ لائن پر کال کریں۔',
  'sos.sent.message_count':
      'آپ کا SOS {{count}} قریبی رضاکاروں کو بھیج دیا گیا۔ فوری مدد کے لیے ہیلپ لائن پر کال کریں۔',
  'sos.sent.title': 'SOS بھیج دیا گیا',
  'sos.snooze': 'سنیوز',
  'sos.snooze.option': '{{min}} کے لیے سنیوز کریں',
  'sos.snooze.pause_hint': 'رنگ اور وائبریشن روکیں',
  'sos.snooze.paused': 'رنگ رکی ہوئی ہے — {{time}}',
  'sos.snooze.recommended': 'تجویز کردہ',
  'sos.snooze.resume': 'جاری رکھیں',
  'sos.snooze.title': 'SOS الرٹس کو سنیوز کریں',
  'sos.status.active': 'SOS فعال ہے',
  'sos.status.notified': 'قریبی رضاکاروں کو مطلع کیا گیا',
  'sos.status.notified_count': '{{count}} قریبی رضاکاروں کو مطلع کیا گیا',
  'sos.tracking.view_map': 'نقشہ دیکھیں',
  'splash.brand': 'CERD کمیونٹی',
  'splash.tagline': 'جب ضرورت ہو کمیونٹی کی مدد',
  'splash.status.preparing': 'CERD کمیونٹی تیار ہو رہی ہے...',
  'splash.status.loading_profile': 'آپ کی پروفائل لوڈ ہو رہی ہے...',
  'splash.status.checking_verification':
      'آپ کی تصدیق کی حیثیت چیک ہو رہی ہے...',
  'splash.status.opening_dashboard':
      'آپ کا رضاکار ڈیش بورڈ کھولا جا رہا ہے...',
  'tracking.arrived': 'رضاکار پہنچ گیا',
  'tracking.distance': 'فاصلہ',
  'tracking.eta': 'متوقع وقت',
  'tracking.live': 'لائیو ٹریکنگ',
  'tracking.no_session': 'کوئی فعال ٹریکنگ سیشن نہیں',
  'tracking.status': 'حالت',
  'tracking.status_arrived': 'پہنچ گیا',
  'tracking.status_enroute': 'راستے میں',
  'tracking.status_waiting': 'انتظار',
  'update.available': 'اپ ڈیٹ دستیاب ہے',
  'update.cancelled': 'ڈاؤن لوڈ منسوخ کر دیا گیا۔ آپ بعد میں اپ ڈیٹ کر سکتے ہیں۔',
  'update.connecting': 'کنیکٹ ہو رہا ہے...',
  'update.downloading': 'اپ ڈیٹ ڈاؤن لوڈ ہو رہی ہے',
  'update.downloading_hint':
      'آپ کے فون کے مطابق چھوٹا پیکج ڈاؤن لوڈ ہو رہا ہے۔',
  'update.incomplete': 'ڈاؤن لوڈ نامکمل لگتا ہے۔ براہ کرم بعد میں دوبارہ کوشش کریں۔',
  'update.installer_failed':
      'انسٹالر نہیں کھل سکا ({{message}})۔ براہ کرم APK دستی طور پر انسٹال کریں۔',
  'update.missing_link': 'ڈاؤن لوڈ لنک دستیاب نہیں ہے۔',
  'update.now': 'ابھی اپ ڈیٹ کریں',
  'update.required': 'اپ ڈیٹ ضروری ہے',
  'update.required_message':
      'ایپ کا نیا ورژن درکار ہے۔ تازہ ترین اصلاحات استعمال کرنے کے لیے اپ ڈیٹ کریں۔',
  'update.version_ready': 'ورژن {{version}} تیار ہے',
  'update.whats_new': 'نیا کیا ہے:',
  'verification.cnic_format_hint': 'فارمیٹ: XXXXX-XXXXXXX-X',
  'verification.complete_profile': 'اپنی پروفائل مکمل کریں',
  'verification.selected_image': 'منتخب تصویر',
  'verification.tap_to_upload': 'اپ لوڈ کرنے کے لیے تھپتھپائیں',
  'verification.tap_to_upload_photo': 'تصویر اپ لوڈ کرنے کے لیے تھپتھپائیں',
  'verification.upload_hint': 'JPG یا PNG، زیادہ سے زیادہ 5MB',
  'verification.upload_hint_photo': 'PNG، JPG، زیادہ سے زیادہ 5MB',
  'volunteer.home.accept_navigate': 'قبول کریں اور نیویگیٹ کریں',
  'volunteer.home.cannot_accept_own': 'آپ اپنی درخواست قبول نہیں کر سکتے۔',
  'volunteer.home.default_name': 'رضاکار صارف',
  'volunteer.home.request_unavailable': 'درخواست ابھی دستیاب نہیں ہے۔',
  'volunteer.home.sos_intro': 'قریبی شخص کو فوری مدد کی ضرورت ہے۔ ابھی جواب دیں۔',
  'toast.server_error': 'کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔',
  'toast.network_error': 'نیٹ ورک کی خرابی۔ براہ کرم اپنا کنکشن چیک کریں۔',
  'toast.timeout_error': 'درخواست میں زیادہ وقت لگا۔ براہ کرم دوبارہ کوشش کریں۔',
  'toast.invalid_input': 'براہ کرم اپنی معلومات چیک کریں اور دوبارہ کوشش کریں۔',
  'toast.session_expired': 'آپ کا سیشن ختم ہو گیا ہے۔ براہ کرم دوبارہ سائن ان کریں۔',
  'toast.not_found': 'آپ جو تلاش کر رہے ہیں وہ نہیں ملا۔',
  'toast.conflict': 'یہ عمل کسی موجودہ چیز سے متصادم ہے۔ براہ کرم کچھ اور کوشش کریں۔',
};
