// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpNcRkh5QWe9Hbpcg65UPu67-htjDJks',
    appId: '1:1019157164328:android:516012563946c54f19a01d',
    messagingSenderId: '1019157164328',
    projectId: 'cerd-95f4e',
    authDomain: 'cerd-95f4e.firebaseapp.com',
    storageBucket: 'cerd-95f4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLpNcRkh5QWe9Hbpcg65UPu67-htjDJks',
    appId: '1:1019157164328:android:516012563946c54f19a01d',
    messagingSenderId: '1019157164328',
    projectId: 'cerd-95f4e',
    storageBucket: 'cerd-95f4e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLpNcRkh5QWe9Hbpcg65UPu67-htjDJks',
    appId: '1:1019157164328:android:516012563946c54f19a01d',
    messagingSenderId: '1019157164328',
    projectId: 'cerd-95f4e',
    storageBucket: 'cerd-95f4e.firebasestorage.app',
    iosClientId: '1019157164328-mf0eugdpmfa3eu96jpt77n2t6js4c81b.apps.googleusercontent.com',
    iosBundleId: 'com.ghaffar.cerd',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLpNcRkh5QWe9Hbpcg65UPu67-htjDJks',
    appId: '1:1019157164328:android:516012563946c54f19a01d',
    messagingSenderId: '1019157164328',
    projectId: 'cerd-95f4e',
    storageBucket: 'cerd-95f4e.firebasestorage.app',
    iosClientId: '1019157164328-mf0eugdpmfa3eu96jpt77n2t6js4c81b.apps.googleusercontent.com',
    iosBundleId: 'com.ghaffar.cerd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLpNcRkh5QWe9Hbpcg65UPu67-htjDJks',
    appId: '1:1019157164328:android:516012563946c54f19a01d',
    messagingSenderId: '1019157164328',
    projectId: 'cerd-95f4e',
    authDomain: 'cerd-95f4e.firebaseapp.com',
    storageBucket: 'cerd-95f4e.firebasestorage.app',
  );
}
