// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK86zhIesnU37g04-e20ckJvtEJQQDm6g',
    appId: '1:1063827736478:web:445a4c444571dc9265388f',
    messagingSenderId: '1063827736478',
    projectId: 'cerd-theemergencyresponse',
    authDomain: 'cerd-theemergencyresponse.firebaseapp.com',
    storageBucket: 'cerd-theemergencyresponse.firebasestorage.app',
    measurementId: 'G-ZZP0VS2QC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzHqCx9MDIDnMcSWSIbc0TnbM5i33PUsQ',
    appId: '1:1063827736478:android:f8efe3ca4b1e42c265388f',
    messagingSenderId: '1063827736478',
    projectId: 'cerd-theemergencyresponse',
    storageBucket: 'cerd-theemergencyresponse.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecPbDGqrPBuhF721DpcUNSBelaprKhnY',
    appId: '1:1063827736478:ios:f3e53a4844d9fa1b65388f',
    messagingSenderId: '1063827736478',
    projectId: 'cerd-theemergencyresponse',
    storageBucket: 'cerd-theemergencyresponse.firebasestorage.app',
    iosClientId: '1063827736478-ecs7covgalle6puu086bod2638jj224l.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypSourceCode',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecPbDGqrPBuhF721DpcUNSBelaprKhnY',
    appId: '1:1063827736478:ios:f3e53a4844d9fa1b65388f',
    messagingSenderId: '1063827736478',
    projectId: 'cerd-theemergencyresponse',
    storageBucket: 'cerd-theemergencyresponse.firebasestorage.app',
    iosClientId: '1063827736478-ecs7covgalle6puu086bod2638jj224l.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypSourceCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK86zhIesnU37g04-e20ckJvtEJQQDm6g',
    appId: '1:1063827736478:web:411dded637063c5665388f',
    messagingSenderId: '1063827736478',
    projectId: 'cerd-theemergencyresponse',
    authDomain: 'cerd-theemergencyresponse.firebaseapp.com',
    storageBucket: 'cerd-theemergencyresponse.firebasestorage.app',
    measurementId: 'G-H86T5CGPGQ',
  );
}
